### ISSUE TITLE
What manages Git?

### ISSUE THREAD

**Issue by joebowbeerxealth** [wmariuss/awesome-devops#5]
What do devops use to manage Git? For example, to create new repos with the proper teams, permissions and protections?

Do they use a terraform provider such as the GitHub provider?

If there are tools that devops use for this, I would appreciate seeing them listed here!

**Comment by wmariuss** [comment]
Hi,

That is the good question. There is no unified git management (I love to see and add it). For example, Github, Gitlab, Gitea and so on in one single tool. Yes, can be Terraform provider for managing this kind of ops, but not sure if there is a single and stable provider to do that. I am sure there is a provider for Github for example.

I remember I built a tool to manage Gitea for example based on files and used it as GitOps method few years ago. I will push it, in case you are interested. In that time there was nothing about it and hard to manage repos, teams, orgs, permissions and so on from UI. That was the reasons to build one.

Let me research on this. Look like a good idea to have it.

**Comment by wmariuss** [comment]
Hello,

Sorry for time long in answering. After some research there is no a standard tool to manage source code platform via code. You can use anything like, Terraform providers or modules if exists (exists but they do not have the whole functionality), or any command line (github has one) or a tool built by your self. I remember in that time for Gitea (source code platform, open source) did not have one for manage via code, and for that i built one (https://github.com/wmariuss/gitea-py, not a best one but works perfect and already used in production with the CI/CD).

So, because there is no a standard tool (better if there is a unified one) i did not put anything regarding the git management in the list. If will appears soon, and is good enough i will definitely put in the list.
